### ISSUE TITLE
Could you upload the trained model

### ISSUE THREAD

**Issue by smolendawid** [nesl/asvspoof2019#4]
Could you please give access to the trained models for a while? I'd like to check some ideas and the access would significantly simplify my research. 

Thank you

**Comment by smolendawid** [comment]
@malzantot @wangziqi000

**Comment by wangziqi000** [comment]
Unfortunately, we lost the old trained models and data due to computer renewal. Maybe you can leave an email address. I know someone who happens to reproduce this work. You can ask whether they have pre-trained models in hand.

**Comment by wangziqi000** [comment]
See /sample_model for pre-trained models. Note that theses models might not be optimal and it is recommended that you fine-tune the settings and train models that best for you need. If some checkpoints does not work due to model structure changes please let me know.

**Comment by smolendawid** [comment]
Thank you a lot, I appreciate
